#!/bin/bash
sudo systemctl stop miner1.service
sudo systemctl stop miner2.service
sudo systemctl stop miner3.service
sudo systemctl stop miner4.service
sudo systemctl stop miner5.service
sudo systemctl stop miner6.service
sudo systemctl stop miner7.service
sudo systemctl stop miner8.service
sudo systemctl stop miner9.service
sudo systemctl stop miner10.service
sudo systemctl stop minerdev.service
sudo systemctl stop minerdevmulti.service
sudo systemctl disable miner1.service
sudo systemctl disable miner2.service
sudo systemctl disable miner3.service
sudo systemctl disable miner4.service
sudo systemctl disable miner5.service
sudo systemctl disable miner6.service
sudo systemctl disable miner7.service
sudo systemctl disable miner8.service
sudo systemctl disable miner9.service
sudo systemctl disable miner10.service
sudo systemctl disable minerdev.service
sudo systemctl disable minerdevmulti.service
echo "no" > /nvezos/set/miners/1status.set
echo "no" > /nvezos/set/miners/2status.set
echo "no" > /nvezos/set/miners/3status.set
echo "no" > /nvezos/set/miners/4status.set
echo "no" > /nvezos/set/miners/5status.set
echo "no" > /nvezos/set/miners/6status.set
echo "no" > /nvezos/set/miners/7status.set
echo "no" > /nvezos/set/miners/8status.set
echo "no" > /nvezos/set/miners/9status.set
echo "no" > /nvezos/set/miners/10status.set
echo "no" > /nvezos/set/miners/devstatus.set